services:
  - type: web
    name: python-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app/main.py"
    envVars:
      - key: ENV
        value: production
      - key: RENDER
        value: true

